/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class conykais_jnilib2_JniTest */

#ifndef _Included_conykais_jnilib2_JniTest
#define _Included_conykais_jnilib2_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     conykais_jnilib2_JniTest
 * Method:    getIntForJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_conykais_jnilib2_JniTest_getIntForJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
