/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <conykais_jnilib2_JniTest.h>
/* Header for class conykais_jnilib2_JniTest */
/*
 * Class:     conykais_jnilib2_JniTest
 * Method:    getIntForJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_conykais_jnilib2_JniTest_getIntForJNI
  (JNIEnv *env, jclass jclazz){
      return 100000;
}
