/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class conykais_jnilib_JniUtils */

#ifndef _Included_conykais_jnilib_JniUtils
#define _Included_conykais_jnilib_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     conykais_jnilib_JniUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_conykais_jnilib_JniUtils_getString
  (JNIEnv *, jobject);
/*
 * Class:     conykais_jnilib_JniUtils
 * Method:    intFromJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_conykais_jnilib_JniUtils_intFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     conykais_jnilib_JniUtils
 * Method:    getStringLenght
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_conykais_jnilib_JniUtils_getStringLenght
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
