/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <conykais_jnilib_JniUtils.h>
/*
 * Class:     conykais_jnilib_JniUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_conykais_jnilib_JniUtils_getString
  (JNIEnv* env, jobject obj){
    return (*env)->NewStringUTF(env,"hello jni");
}
/*
 * Class:     conykais_jnilib_JniUtils
 * Method:    intFromJNI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_conykais_jnilib_JniUtils_intFromJNI
  (JNIEnv *env, jobject obj){
    return 10;
}
/*
 * Class:     conykais_jnilib_JniUtils
 * Method:    getStringLenght
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_conykais_jnilib_JniUtils_getStringLenght
  (JNIEnv * env, jobject obj, jstring str){
    return (*env)->GetStringLength(env,str);
}